### ISSUE TITLE
Add husky

### ISSUE THREAD

**Issue by FoseFx** [helpwave/rest-api#8]
[Husky](https://github.com/automation-co/husky) is a tool that manages git hooks like `pre-commit` and so on.

To prevent time wasted on a broken ci we should install husky and run the linter before a commit is made.

**Comment by Friedjof** [comment]
As I understand Husky it is not so powerful for Go projects. But I have defined some hooks now. You can see them here: https://github.com/helpwave/rest-api/tree/issue/8-add_husky/.husky/hooks

**Comment by Florian-Sabonchi** [comment]
Still someone working on it? ore shoud i close
